language: java
jdk: oraclejdk11

before_install:
  - chmod +x gradlew

script: >-
  ./gradlew clean checkstyleMain checkstyleTest test jacocoTestReport coveralls

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)